services:
  - type: web
    name: banking-backend
    plan: free
    runtime: docker
    buildCommand: "./mvnw clean install"
    
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d78lkkedqaus73d2df3g-a.oregon-postgres.render.com:5432/dpg-d78lkkedqaus73d2df3g
      - key: SPRING_DATASOURCE_USERNAME
        value: banking_db_62aa_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: UA2CaepjciJyzRa16GhOtLgAOMjdLOYZ
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
