spring.datasource.url=jdbc:postgresql://dpg-d78lkkedqaus73d2df3g-a.oregon-postgres.render.com:5432/banking_db_62aa
spring.datasource.username=banking_db_62aa_user
spring.datasource.password=UA2CaepjciJyzRa16GhOtLgAOMjdLOYZ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect